# Generated by Django 5.1.1 on 2025-01-30 11:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_info',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
