# Generated by Django 5.1.5 on 2025-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.jpeg', help_text='Upload category image (Recommended: 300x300px)', upload_to='categories'),
        ),
    ]
