# Generated by Django 5.1.1 on 2025-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_category_options_product_is_hot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload category image (Recommended: 300x300px)', null=True, upload_to='categories'),
        ),
    ]
