# Generated by Django 5.1.1 on 2025-01-30 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_alter_product_extra_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
