# Generated by Django 5.1.1 on 2025-02-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_product_category_discount_applied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
