# Generated by Django 5.1.5 on 2025-04-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_deal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
