# Generated by Django 5.1.5 on 2025-05-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
    ]
