# Generated by Django 5.1.5 on 2025-06-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_remove_contact_address_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('PayPal', 'PayPal'), ('Khalti', 'Khalti'), ('Cash on Delivery', 'Cash on Delivery')], default='Esewa', max_length=50),
        ),
    ]
