# Generated by Django 5.2.4 on 2026-03-08 15:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_newslettersubscriber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommenderTrainingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=64, unique=True)),
                ('last_trained_event_id', models.BigIntegerField(default=0)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='UserActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('event_type', models.CharField(choices=[('impression', 'impression'), ('dwell', 'dwell'), ('hover', 'hover'), ('click', 'click'), ('quick_view', 'quick_view'), ('add_to_cart', 'add_to_cart'), ('wishlist', 'wishlist')], db_index=True, max_length=24)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('page', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='shopapp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='shopapp_use_user_id_2ea570_idx'), models.Index(fields=['anon_id', 'created_at'], name='shopapp_use_anon_id_1b132f_idx'), models.Index(fields=['fingerprint', 'created_at'], name='shopapp_use_fingerp_e87909_idx'), models.Index(fields=['product', 'created_at'], name='shopapp_use_product_b6ed3a_idx'), models.Index(fields=['event_type', 'created_at'], name='shopapp_use_event_t_6d1b39_idx')],
            },
        ),
    ]
