# Generated by Django 5.2.4 on 2026-03-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_recommendertrainingstate_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomIndexState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='products', max_length=64, unique=True)),
                ('num_bits', models.PositiveIntegerField(default=262144)),
                ('num_hashes', models.PositiveIntegerField(default=7)),
                ('data', models.BinaryField(default=b'')),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBloomSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bits', models.PositiveIntegerField(default=2048)),
                ('num_hashes', models.PositiveIntegerField(default=7)),
                ('data', models.BinaryField(default=b'')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloom_signature', to='shopapp.product')),
            ],
        ),
    ]
