# Generated by Django 5.2.4 on 2026-04-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_bloomindexstate_productbloomsignature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloomIndexState',
        ),
        migrations.DeleteModel(
            name='ProductBloomSignature',
        ),
    ]
