# Generated by Django 5.2.4 on 2026-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_delete_bloomindexstate_delete_productbloomsignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('recommended_product_ids', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
