# Generated by Django 5.2.4 on 2026-04-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_review_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_edited',
        ),
    ]
