# Generated by Django 5.2.4 on 2026-06-21 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_remove_review_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage for all products in this category (e.g., 10 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0, message='Discount percentage cannot be negative.'), django.core.validators.MaxValueValidator(100.0, message='Discount percentage cannot exceed 100.')]),
        ),
    ]
