"""
Django settings for Bikrante project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
EMAIL = os.getenv("EMAIL")
PASSKEY=os.getenv("PASSKEY")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret-key-for-dev")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
 "*",
]


# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'jet.dashboard',  # this should go BEFORE 'jet'
    'jet',             # Django JET UI
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shopapp.apps.ShopappConfig',
    'django_ckeditor_5',  #! CKEditor 5 - modern rich text editor
    'django_htmx',##!for django-htmx
    'paypal.standard.ipn',  #! Add this line for PayPal IPN
]
# JAZZMIN_SETTINGS = {
#     "theme": "darkly",  # Enable Dark Mode
# }
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_htmx.middleware.HtmxMiddleware", ##!for django-htmx

]

ROOT_URLCONF = 'Bikrante.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',  
            ],
        },
    },
]

WSGI_APPLICATION = 'Bikrante.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Update static files configuration
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'shopapp/static'),  # App-specific static files
]

# Directory where static files will be collected for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

##! CKEditor 5 settings
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 
            '|', 'outdent', 'indent', '|', 'blockQuote', 'insertTable', 'mediaEmbed',
            'undo', 'redo', '|', 'sourceEditing'
        ],
        'height': 300,
        'width': '100%',
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3', '|',
            'bulletedList', 'numberedList', '|',
            'blockQuote', 'insertTable', '|',
            'outdent', 'indent', '|',
            'undo', 'redo'
        ],
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', 'bulletedList', 'numberedList', '|',
            'fontSize', 'fontColor', 'fontBackgroundColor', '|',
            'alignment:left', 'alignment:right', 'alignment:center', 'alignment:justify', '|',
            'blockQuote', 'insertTable', 'mediaEmbed', 'codeBlock', 'htmlEmbed', '|',
            'outdent', 'indent', '|', 'undo', 'redo', '|', 'sourceEditing'
        ],
        'height': 300,
        'width': '100%',
    }
}

# Custom CSS class for tables in CKEditor 5
CKEDITOR_5_CUSTOM_CSS = ''  # Add custom CSS if needed

# PayPal Settings
PAYPAL_TEST = True
PAYPAL_BUSINESS_EMAIL = 'sb-jkhmq29131294@business.example.com'  # Business account
PAYPAL_RECEIVER_EMAIL = 'sb-jkhmq29131294@business.example.com'  # Same as business email
PAYPAL_CURRENCY = "USD"
NPR_TO_USD_RATE = 132.50

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

##! added for django mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = EMAIL  # your Gmail address
EMAIL_HOST_PASSWORD = PASSKEY  # the 16-character app password from Google
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL

#! for django jet
JET_DASHBOARD_APP = 'shopapp'
JET_DASHBOARD_ENABLE = True
JET_INDEX_DASHBOARD = 'shopapp.dashboard.CustomIndexDashboard'
JET_DEFAULT_INDEX_DASHBOARD = 'shopapp.dashboard.CustomIndexDashboard'

##! Production Security Settings (enable when deploying with HTTPS)
# Uncomment these when you have HTTPS enabled in production:
# SESSION_COOKIE_SECURE = True  # Only send cookies over HTTPS
# CSRF_COOKIE_SECURE = True       # Only send CSRF cookie over HTTPS
# SECURE_SSL_REDIRECT = True      # Redirect all HTTP to HTTPS
# SECURE_HSTS_SECONDS = 31536000  # Enable HSTS for 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'        # Prevent clickjacking

##! CKEditor 5 Upload Security Settings
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"  # Only staff users can upload files
CKEDITOR_5_ALLOW_ALL_FILE_TYPES = False      # Restrict file types
CKEDITOR_5_UPLOAD_FILE_TYPES = ['image/jpeg', 'image/png', 'image/gif', 'image/webp']  # Allowed image types
CKEDITOR_5_MAX_FILE_SIZE = 5242880  # 5MB max file size
